#' getClassifications output generator
#'
#' Takes in a dataframe generated by "generate_snp_data" and returns each subject classified with full classification paths
#' @param source_df The snp_data generated dataframe
#' @keywords path list haplogroup classification
#' @export
#' @examples
#' mapfile <- system.file("extdata","HapMap_Mito_Seq_QC_2.map",package="HiMC")
#' pedfile <- system.file("extdata","HapMap_Mito_Seq_QC_2.ped",package="HiMC")
#' snpfile <- generate_snp_data(mapfile,pedfile)
#' classifications <- getClassifications(snpfile)

getClassifications <- function(source_df) {
  full_paths <- by(source_df,1:nrow(source_df),getPathList,simplify=FALSE)
  source_df$full_path <- unlist(full_paths)
  source_df$haplogroup <- unlist(lapply(source_df$full_path,getGroupFromPath))
  final_frame <- source_df[,names(source_df) %in% c("Individual","haplogroup","full_path")]
}
